### ISSUE TITLE
General questions about SemanticCodeSearch

### ISSUE THREAD

**Issue by wasiahmad** [FSoft-AI4Code/HyperAgent#3]
I am curious about [SemanticCodeSearchTool](https://github.com/FSoft-AI4Code/RepoPilot/blob/main/src/repopilot/tools.py#L390). 

```
db = Chroma(persist_directory=db_path, embedding_function=OpenAIEmbeddings(disallowed_special=()))
```

Can we plugin any embedding model instead of `OpenAIEmbeddings`? For example, use of [HuggingFaceEmbeddings](https://integrations.langchain.com/embeddings?integration_name=HuggingFaceEmbeddings).

I have a few questions regarding the use of SemanticCodeSearch for RepoPilot.

1. Does current implementation use SemanticCodeSearch? I have gone through the code and it seems like semantic search is not used/explored yet. If it is used, can you provide some detail how repositories are indexed or stored in DB (whole files or they are segmented)?
2. Which part of RepoPilot uses semantic search? Planning, Analysis, or Navigation? I am guessing it is the navigator because it takes tools where we can include the SemanticCodeSearchTool.

**Comment by huyphan168** [comment]
Hi, you can use any embedding model beside OpenAIEmbeddings. 
1. We observed that current implementation of Semantic Code Search tool causes the pilot using this tool too frequently, so currently, I disabled it. But in the future, we will try to integrate this tool in the flow. The files are iteratively segmented with language-specific parser (you can find it in the codebase), then indexed.
2. Currently, Navigator is using the semantic code search tool.
